### ISSUE TITLE
Speed limit?

### ISSUE THREAD

**Issue by HammyHavoc** [deblockt/hass-aria2#2]
Would be great to be able to limit download speeds via Home Assistant.

**Comment by deblockt** [comment]
Hi, thanks for this feature request. 

This project is a build in progress, I try to have a stable first version before adding new feature.

**Comment by deblockt** [comment]
For this feature, I think that a configuration screen on integration panel can be fine. 
We should be able to set the following options https://aria2.github.io/manual/en/html/aria2c.html#aria2.changeGlobalOption

**Comment by deblockt** [comment]
This issue is fixed with the version 0.2.6
