### ISSUE TITLE
Cannot add an integration

### ISSUE THREAD

**Issue by bearpawmaxim** [deblockt/hass-aria2#6]
Hello!
Trying to add an integration but getting the "Config flow could not be loaded: undefined" error.
Using Homeassistant supervised, version is 2022.7.7.

**Comment by bearpawmaxim** [comment]
Okay. Installed through hacs and it worked

**Comment by deblockt** [comment]
Hi @bearpawmaxim thanks to report this issue. Can you share logs associated with thé error. Maybe that I can avoid this type of error on non hacs installation. 

Thanks

**Comment by bearpawmaxim** [comment]
Hi @deblockt!
Unfortunately, there was no logs at all (in Settings->System->Logs)...
I just cloned the repo and copied the aria2 directory to my custom_components folder. Maybe, that was the cause of the error?
