### ISSUE TITLE
Add more details to download_state_updated event

### ISSUE THREAD

**Issue by bearpawmaxim** [deblockt/hass-aria2#7]
Hi!
I have created the automation that listens for a `download_state_updated` event and sends a message to telegram with download gid and state, but that is not very helpful because I can't understand what was downloaded (I don't know the file name that was downloaded).
![Screenshot_20220731-093247](https://user-images.githubusercontent.com/7537528/182013368-bc92ae9c-2bff-49cb-817f-511bfc5ae433.jpg) 

It would be fine to have more info about the download in the `download_state_updated` event or to have an ability to get the download details by it's gid.

**Comment by bearpawmaxim** [comment]
Thanks a lot!)

**Comment by deblockt** [comment]
You can use the 0.2.7 version https://github.com/deblockt/hass-aria2/releases/tag/0.2.7
