### ISSUE TITLE
Add prefix to sensor names

### ISSUE THREAD

**Issue by bearpawmaxim** [deblockt/hass-aria2#9]
I suggest adding the prefix `aria_` or `aria2_` to the sensor names, since the current names may conflict with the names of existing sensors (especially the download_speed and upload_speed sensors)

**Comment by deblockt** [comment]
What do you think about prefixing with the host of the aria server?

**Comment by deblockt** [comment]
something like `sensor.aria_192_168_1_57_upload_speed`

**Comment by bearpawmaxim** [comment]
> What do you think about prefixing with the host of the aria server?
For support of multiple aria2 integrations, right?
Maybe add an integration instance name (for existing integrations use host name)?

**Comment by deblockt** [comment]
fixed with version [0.3.0](https://github.com/deblockt/hass-aria2/releases/tag/0.3.0)
